manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
    - name: eesawiththeshot
      url-base: https://github.com/EesaWithTheShot
  projects:
    - name: zmk
      remote: eesawiththeshot
      revision: ssd1322fix-zmk
      import: app/west.yml
  self:
    path: config
